# Generated by Django 5.2.7 on 2025-11-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kudos_left',
            field=models.IntegerField(default=3),
        ),
    ]
